server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    prefer-ip-address: true

yunconfig: è·Ÿæˆ‘ä¸€èµ·è¯»ï¼šå¤§è„‘æ–§ğŸ¯ï¼Œå°å‡¶è®¸ğŸ¿ï¸ï¼Œ å¤§èŸ’é‹ğŸï¼Œå°æ°‘é˜³ğŸ‘ï¼Œ å¤§è¥¿å‡ ğŸ¦ï¸ï¼Œå°ç™½å»ğŸ‡ï¼Œ æ²¡å‘æ€’ğŸ¦Œï¼Œå¤§é£é¦•ğŸºï¼Œ å°çŒ´å‡ ğŸ’ï¼Œå¤§æ£®æ£®ğŸ¦ï¼Œ å°è„‘è®¸ğŸ€ï¼Œå°é¸­å‡ ğŸ¦†ï¼Œ å°æ–§é‡ŒğŸ¦Šï¼Œå°èœœå“„ğŸï¼Œ æ¯›æ¯›ç©·ğŸ›ï¼Œå°æœºå±…ğŸ•·ï¼Œ å°æµ·ç–¼ğŸ¬ï¼Œå‘ç¦è¶ğŸ¦‹ï¼Œå¤§å§œé±¼ğŸ™ï¼Œå¢™é¢ˆæ€’ğŸ¦’â—
#spring:
#  security:
#     basic:
#       enabled: true
#     user:
#        name: abc
#        password: 123

#  server:
#      enableSelfPreservation: false